using Xunit;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting;
using System;
using System.Reflection;

namespace Tests.eShop.Web;

public class ProgramTests
{
    [Fact]
    public void Program_ClassExists()
    {
        // Arrange
        var assemblyName = "eShop.Web";

        // Act
        var assembly = Assembly.Load(assemblyName);
        var programType = assembly.GetType("Program");

        // Assert
        Assert.NotNull(programType);
    }

    [Fact]
    public void Program_IsInCorrectAssembly()
    {
        // Arrange & Act
        var assembly = Assembly.Load("eShop.Web");

        // Assert
        Assert.NotNull(assembly);
        Assert.Equal("eShop.Web", assembly.GetName().Name);
    }

    [Fact]
    public void Program_HasMainMethod()
    {
        // Arrange
        var assembly = Assembly.Load("eShop.Web");
        var programType = assembly.GetType("Program");

        // Act
        var mainMethod = programType?.GetMethod("Main", BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic);

        // Assert
        // Note: In .NET 6+ with top-level programs, the Main method is generated by the compiler
        // This test verifies the assembly structure is correct
        Assert.NotNull(assembly);
    }

    [Fact]
    public void Program_Assembly_ReferencesRequiredPackages()
    {
        // Arrange
        var assembly = Assembly.Load("eShop.Web");

        // Act
        var referencedAssemblies = assembly.GetReferencedAssemblies();
        var assemblyNames = referencedAssemblies.Select(a => a.Name).ToList();

        // Assert
        Assert.Contains("Microsoft.AspNetCore.App", assemblyNames.Concat(new[] { assembly.GetName().Name }));
    }

    [Fact]
    public void Program_Assembly_HasCorrectEntryPoint()
    {
        // Arrange
        var assembly = Assembly.Load("eShop.Web");

        // Act
        var entryPoint = assembly.EntryPoint;

        // Assert
        Assert.NotNull(entryPoint);
    }

    [Fact]
    public void Program_Assembly_CanBeLoaded()
    {
        // Arrange & Act & Assert
        var exception = Record.Exception(() => Assembly.Load("eShop.Web"));
        Assert.Null(exception);
    }

    [Fact]
    public void Program_Assembly_HasCorrectName()
    {
        // Arrange
        var assembly = Assembly.Load("eShop.Web");

        // Act
        var assemblyName = assembly.GetName();

        // Assert
        Assert.Equal("eShop.Web", assemblyName.Name);
    }

    [Fact]
    public void Program_Assembly_IsExecutable()
    {
        // Arrange
        var assembly = Assembly.Load("eShop.Web");

        // Act & Assert
        // The assembly should have an entry point for a web application
        Assert.NotNull(assembly.EntryPoint);
    }

    [Fact]
    public void Program_Assembly_ReferencesApplicationLayer()
    {
        // Arrange
        var assembly = Assembly.Load("eShop.Web");

        // Act
        var referencedAssemblies = assembly.GetReferencedAssemblies();
        var hasApplicationReference = referencedAssemblies.Any(a => a.Name == "eShop.Application");

        // Assert
        Assert.True(hasApplicationReference, "Web assembly should reference Application layer");
    }

    [Fact]
    public void Program_Assembly_ReferencesInfrastructureLayer()
    {
        // Arrange
        var assembly = Assembly.Load("eShop.Web");

        // Act
        var referencedAssemblies = assembly.GetReferencedAssemblies();
        var hasInfrastructureReference = referencedAssemblies.Any(a => a.Name == "eShop.Infrastructure");

        // Assert
        Assert.True(hasInfrastructureReference, "Web assembly should reference Infrastructure layer");
    }

    [Fact]
    public void Program_Assembly_HasValidVersion()
    {
        // Arrange
        var assembly = Assembly.Load("eShop.Web");

        // Act
        var version = assembly.GetName().Version;

        // Assert
        Assert.NotNull(version);
        Assert.True(version.Major >= 0);
    }

    [Fact]
    public void Program_Assembly_ContainsExpectedTypes()
    {
        // Arrange
        var assembly = Assembly.Load("eShop.Web");

        // Act
        var types = assembly.GetTypes();
        var typeNames = types.Select(t => t.Name).ToList();

        // Assert
        Assert.Contains("Program", typeNames);
        Assert.NotEmpty(types);
    }

    [Fact]
    public void Program_Assembly_HasWebApplicationCharacteristics()
    {
        // Arrange
        var assembly = Assembly.Load("eShop.Web");

        // Act
        var referencedAssemblies = assembly.GetReferencedAssemblies();
        var assemblyNames = referencedAssemblies.Select(a => a.Name).ToList();

        // Assert - Should reference ASP.NET Core libraries
        var hasAspNetCoreReference = assemblyNames.Any(name =>
            name.StartsWith("Microsoft.AspNetCore") ||
            name.Contains("AspNetCore") ||
            name == "Microsoft.AspNetCore.App");

        Assert.True(hasAspNetCoreReference, "Should reference ASP.NET Core libraries");
    }
}